name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "🚀 Features"
    label: "enhancement"
  - title: "🐛 Bug Fixes"
    label: "bug"
  - title: "🧰 Maintenance"
    label: "chore"
  - title: "📦 Dependencies"
    label: "dependencies"
  - title: "⚡️🩹 Hotfix"
    label: "hotfix"
change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - "major"
  minor:
    labels:
      - "minor"
      - "enhancement"
  default: patch
autolabeler:
  - label: "chore"
    branch:
      - '/chore\/.+/'
  - label: "bug"
    branch:
      - '/bugfix\/.+/'
  - label: "enhancement"
    branch:
      - '/feature\/.+/'
  - label: "hotfix"
    branch:
      - '/hotfix\/.+/'
  - label: "skip-changelog"
    branch:
      - "/main/"
      - "/pre-production/"
      - "/production/"
exclude-labels:
  - "skip-changelog"
template: |
  ## Changes
  $CHANGES
include-pre-releases: false
filter-by-commitish: true
