name: リリース対象動作確認
description: リリース対象動作確認のためのテンプレート
title: "yyyy/mm/ddリリース対象の動作確認を実施する"

body:
  - type: markdown
    attributes:
      value: |
        ### 説明

        リリース対象の動作確認を実施するためのテンプレートです。

        テスト対象は以下の基準で判断してください。
        - ユーザーに影響があるもの
          - 表示内容
          - 表示条件
          - 表示タイミング

        プロジェクト内のタスクはリリースに向けてテストを行うためテストは不要です

  - type: textarea
    id: test_target
    attributes:
      label: テスト対象
      description: テストが必要なものを記載してください
      value: |
        - [ ] bizreach-inc/cwr#
        - [ ] bizreach-inc/cwr#
        - [ ] bizreach-inc/cwr#

  - type: textarea
    id: ignore_target
    attributes:
      label: テスト不要
      description: テストが不要なものを記載してください
      value: |
        - bizreach-inc/cwr#
        - bizreach-inc/cwr#
        - bizreach-inc/cwr#

  - type: textarea
    id: project_task
    attributes:
      label: プロジェクトタスク
      description: プロジェクトタスクを記載してください
      value: |
        - bizreach-inc/cwr#
        - bizreach-inc/cwr#
        - bizreach-inc/cwr#
