name: Release Drafter - Generate Release Notes

on:
  push:
    branches:
      - pre-production
      - production

run-name: ${{ format('Generate Release Notes {0}', github.sha) }}

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # リリースを作成するために必要
      contents: write
      # プルリクエストにラベルをつけるために必要
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 検証用リリースの設定
          prerelease: ${{ github.ref == 'refs/heads/pre-production' }}
          prerelease-identifier: alpha
          # 本番リリースの設定
          publish: false
          # プルリクエストイベントのときにラベル設定を行う
          disable-autolabeler: true
          commitish: "refs/heads/production"
