name: Release Drafter

on:
  push:
    branches:
      - pre-production
      - production

  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      # リリースを作成するために必要
      contents: write
      # プルリクエストにラベルをつけるために必要
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # 検証用リリースの設定
          prerelease: ${{ github.event_name == 'push' && github.ref == 'refs/heads/pre-production' }}
          prerelease-identifier: alpha
          # 本番リリースの設定
          publish: ${{ github.event_name == 'push' && github.ref == 'refs/heads/production' }}
          # PUSHイベントのときにリリースを作成する
          disable-releaser: ${{ github.event_name != 'push' }}
          # プルリクエストイベントのときにラベル設定を行う
          disable-autolabeler: ${{ github.event_name != 'pull_request' }}
