name: Release Drafter

on:
  push:
    branches:
      - pre-production
      - production
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: write

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          prerelease: ${{ github.event_name == 'push' && github.ref == 'refs/heads/pre-production' }}
          prerelease-identifier: alpha
